# Generated by Django 5.2.7 on 2025-11-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("id_cliente", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
            ],
            options={"db_table": "clientes", "managed": False,},
        ),
    ]
